# Generated by Django 3.1.2 on 2020-11-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forparent',
            fields=[
                ('b_id', models.AutoField(db_column='no', primary_key=True, serialize=False)),
                ('Name', models.CharField(db_column='Name', max_length=255)),
                ('Title', models.CharField(db_column='Title', max_length=255)),
                ('Location', models.CharField(db_column='Location', max_length=50)),
                ('Date', models.DateTimeField(db_column='Date')),
            ],
            options={
                'db_table': 'forparent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question1',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('Title', models.CharField(db_column='Title', max_length=255)),
                ('Date', models.DateTimeField(db_column='Date')),
                ('Text', models.CharField(db_column='Text', max_length=255)),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Forsitter',
            fields=[
                ('no', models.AutoField(db_column='no', primary_key=True, serialize=False)),
                ('Name', models.CharField(db_column='Name', max_length=255)),
                ('Title', models.CharField(db_column='Title', max_length=255)),
                ('Location', models.CharField(db_column='Location', max_length=255)),
                ('Date', models.DateTimeField(db_column='Date')),
            ],
        ),
    ]
